"""Data schema for analytical insights (Phase 3)."""
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field

InsightType = Literal[
    "segment_difference",
    "correlation",
    "trend",
    "outlier",
    "data_quality"
]

ConfidenceLevel = Literal["high", "medium", "low"]

class Insight(BaseModel):
    """
    Standardized atomic insight generated by the agent.
    Grounded strictly in computed tool results or data cleaning reports.
    """
    id: str
    type: InsightType
    title: str
    summary: str
    metric_values: Dict[str, Any] = Field(default_factory=dict)
    evidence_step: Optional[int] = None
    significance: Optional[float] = None
    effect_size: Optional[float] = None
    n_used: int = 0
    n_excluded: int = 0
    exclusion_rate: float = 0.0
    confidence: ConfidenceLevel = "high"
    caveats: List[str] = Field(default_factory=list)
    chart_spec: Optional[Dict[str, Any]] = None
    impact_score: float = Field(default=0.5, ge=0.0, le=1.0)
